/**
 * Render the tokens as CSS for the web app.
 *
 * TypeScript is the source of truth and CSS is the artifact, not the reverse:
 * templating a string needs no dependencies, whereas parsing CSS back into
 * typed objects needs a parser and loses authoring-time types. TS is also the
 * only format BOTH platforms consume natively — React Native cannot read CSS.
 *
 * The output is committed (`apps/web/src/app/tokens.generated.css`) rather than
 * built on demand, so the web build needs no extra step and a reviewer can see
 * exactly what changed in a diff. `scripts/tokens.mjs` fails CI if the
 * committed file drifts from what this produces.
 */
import { palette, type RampName } from '../tokens/palette.ts';
import { dark, light, type SemanticScheme } from '../tokens/semantic.ts';

/**
 * `cardForeground` -> `card-foreground`, `chart1` -> `chart-1`.
 * Digits need their own boundary; without it `chart1` becomes `chart1` and the
 * generated variable silently stops matching the one shadcn components use.
 */
export function cssVarName(name: string): string {
  return name
    .replace(/([A-Z])/g, '-$1')
    .replace(/([0-9]+)/g, '-$1')
    .toLowerCase();
}

const RAMP_ORDER: readonly RampName[] = [
  'slate', 'red', 'orange', 'yellow', 'green', 'teal', 'sky', 'blue', 'purple', 'rose',
];

function renderPalette(): string {
  const lines: string[] = [
    `  --color-white: ${palette.white};`,
    `  --color-black: ${palette.black};`,
  ];
  for (const ramp of RAMP_ORDER) {
    lines.push('');
    for (const [stop, value] of Object.entries(palette[ramp])) {
      lines.push(`  --color-${ramp}-${stop}: ${value};`);
    }
  }
  return lines.join('\n');
}

function renderScheme(scheme: SemanticScheme, extra: readonly string[] = []): string {
  const lines = [...extra];
  for (const [name, value] of Object.entries(scheme)) {
    lines.push(`  --${cssVarName(name)}: ${value};`);
  }
  return lines.join('\n');
}

/** The full contents of apps/web/src/app/tokens.generated.css. */
export function renderCss(): string {
  return `/* GENERATED by packages/ui — do not edit.
 * Source: packages/ui/src/tokens/*.ts   Regenerate: pnpm tokens:build
 *
 * Editing this file directly will be reverted by \`pnpm tokens:check\` in CI.
 * Mobile reads the same tokens from TypeScript, so a value changed only here
 * would silently desync the two platforms — which is the drift this replaces.
 */

/* Raw ramps. Standard Tailwind for slate/red/yellow/teal/sky/blue/rose; custom
 * tinted ramps for orange/green/purple. Explicit so direct utilities
 * (e.g. bg-green-500) match the palette exactly. */
@theme {
${renderPalette()}
}

/* Semantic tokens — light. */
:root {
${renderScheme(light, ['  --radius: 0.625rem;', ''])}
}

/* Semantic tokens — dark. Defined for fidelity; the app ships light-only and
 * nothing adds the .dark class today. NOTE: --background and --primary are both
 * purple-900 here, carried over from the original export — a primary button
 * would be invisible. Fix that when dark mode is actually adopted. */
.dark {
${renderScheme(dark)}
}
`;
}
