export const qk = {
  communities: ['communities'] as const,
  ownedCommunities: ['communities', 'owned'] as const,
  community: (id: string) => ['community', id] as const,
  members: (id: string) => ['community', id, 'members'] as const,
  permissions: (id: string) => ['community', id, 'permissions'] as const,
  posts: (id: string) => ['community', id, 'posts'] as const,
  post: (postId: string) => ['post', postId] as const,
  comments: (postId: string) => ['post', postId, 'comments'] as const,
  reviews: (id: string) => ['community', id, 'reviews'] as const,
  canReview: (id: string) => ['community', id, 'can-review'] as const,
  requests: (id: string) => ['community', id, 'requests'] as const,
  standing: (id: string) => ['community', id, 'standing'] as const,
  memberCount: (id: string) => ['community', id, 'member-count'] as const,
  suggested: ['communities', 'suggested'] as const,
  canCreate: ['communities', 'can-create'] as const,
  defaultCommunity: ['communities', 'default'] as const,
  groups: (cid: string) => ['community', cid, 'groups'] as const,
  archivedGroups: (cid: string) => ['community', cid, 'groups', 'archived'] as const,
  group: (id: string) => ['group', id] as const,
  groupMembers: (id: string) => ['group', id, 'members'] as const,
  groupMemberList: (id: string) => ['group', id, 'member-list'] as const,
  groupSeasons: (id: string) => ['group', id, 'seasons'] as const,
  groupInvitations: (id: string) => ['group', id, 'invitations'] as const,
  canCreateGroup: (cid: string) => ['community', cid, 'can-create-group'] as const,
  myGroups: ['my-groups'] as const,
  myGroupsWithArchived: ['my-groups', 'with-archived'] as const,
  // Under the my-groups prefix, so invalidating qk.myGroups refreshes it too.
  eventCreatableGroups: (communityId: string) => ['my-groups', 'event-creatable', communityId] as const,
  events: (groupId: string) => ['group', groupId, 'events'] as const,
  communityEvents: (communityId: string) => ['community', communityId, 'events'] as const,
  /** Prefix of every My Events list: invalidating it refreshes every tab, past or not. */
  myEventsAll: ['my-events'] as const,
  myEvents: (filter: 'all' | 'organizing' | 'going' | 'pending', includePast = false) =>
    (includePast ? (['my-events', filter, 'past'] as const) : (['my-events', filter] as const)),
  /** The viewer's waiting-list / interested rows — under the prefix, refreshed with the lists. */
  myEventStatuses: ['my-events', 'statuses'] as const,
  eventInvitedPlayers: (id: string) => ['event', id, 'invited-players'] as const,
  event: (id: string) => ['event', id] as const,
  eventParticipants: (id: string) => ['event', id, 'participants'] as const,
  eventInvitations: (id: string) => ['event', id, 'invitations'] as const,
  eventActivity: (id: string) => ['event', id, 'activity'] as const,
  eventTeams: (id: string) => ['event', id, 'teams'] as const,
  eventCourts: (id: string) => ['event', id, 'courts'] as const,
  eventSeries: (id: string) => ['event', id, 'series'] as const,
  eventRounds: (id: string) => ['event', id, 'rounds'] as const,
  eventMatches: (id: string) => ['event', id, 'matches'] as const,
  eventStandings: (id: string) => ['event', id, 'standings'] as const,
  eventTimer: (id: string) => ['event', id, 'timer'] as const,
  eventResultSummary: (id: string) => ['event', id, 'result-summary'] as const,
  partnerRequests: (id: string) => ['event', id, 'partner-requests'] as const,
  partnerCandidates: (id: string) => ['event', id, 'partner-candidates'] as const,
  /** Under the event prefix: the start sheet's blockers and warnings (0122). */
  eventStartCheck: (id: string) => ['event', id, 'start-check'] as const,
  /** Under the event prefix: the Invite screen's search (0122). */
  eventInviteCandidates: (id: string, q: string) => ['event', id, 'invite-candidates', q] as const,
  /** Under the event prefix: a recurring event's next occurrences (0123 / UX-MEVT-22). */
  eventNextOccurrences: (id: string) => ['event', id, 'next-occurrences'] as const,
  canCreateEvent: (groupId: string) => ['group', groupId, 'can-create-event'] as const,
  canInviteToGroup: (groupId: string) => ['group', groupId, 'can-invite'] as const,
  groupInvitationPreview: (groupId: string) => ['group', groupId, 'invitation-preview'] as const,
  mayCreateGroup: (cid: string) => ['community', cid, 'may-create-group'] as const,
  eventRanking: (groupId: string, seasonId: string) =>
    ['group', groupId, 'ranking', seasonId] as const,
  groupRanking: (seasonId: string) => ['group-ranking', seasonId] as const,
  exploreCommunities: ['explore', 'communities'] as const,
  exploreGroups: ['explore', 'groups'] as const,
  exploreEvents: ['explore', 'events'] as const,
  explorePlayers: ['explore', 'players'] as const,
  exploreCommunitiesList: ['explore', 'communities', 'list'] as const,
  exploreGroupsList: ['explore', 'groups', 'list'] as const,
  exploreEventsList: ['explore', 'events', 'list'] as const,
  explorePlayersList: ['explore', 'players', 'list'] as const,
  notifications: ['notifications'] as const,
  notificationsUnread: ['notifications', 'unread'] as const,
  partnerRequestSummary: ['notifications', 'partner-summary'] as const,
  incomingPartnerRequests: ['notifications', 'partner-requests', 'incoming'] as const,
  profile: (id: string) => ['profile', id] as const,
  following: (id: string) => ['profile', id, 'following'] as const,
  followers: (id: string) => ['profile', id, 'followers'] as const,
  myProfile: (id: string) => ['profile', id, 'edit'] as const,
  profileSearch: (q: string) => ['profile', 'search', q] as const,
  // Nested under qk.profile(id) so invalidating a profile refreshes its sections too.
  profileGroups: (id: string) => ['profile', id, 'groups'] as const,
  profileResults: (id: string) => ['profile', id, 'results'] as const,
  profileBadges: (id: string) => ['profile', id, 'badges'] as const,
  myBlocks: (q: string) => ['blocks', 'mine', q] as const,
  mySettings: (id: string) => ['user-settings', id] as const,
  authProviders: (id: string) => ['auth-providers', id] as const,
  streamToken: (uid: string) => ['stream-token', uid] as const,
  venues: ['venues'] as const,
  searchVenues: (q: string, all = false) => ['venues', 'search', q, all] as const,
  adminVenues: (q: string) => ['venues', 'admin', q] as const,
  venueRegistry: (q: string) => ['venues', 'registry', q] as const,
  venue: (id: string) => ['venues', 'detail', id] as const,
  venueCourts: (id: string) => ['venues', 'detail', id, 'courts'] as const,
  isSuperAdmin: (uid: string) => ['super-admin', uid] as const,
  blastTemplates: ['blast-templates'] as const,
  eventBlasts: (id: string) => ['event', id, 'blasts'] as const,
  blastDeliveries: (id: string) => ['event', id, 'blast-deliveries'] as const,
  canCustomizeBlast: (id: string) => ['event', id, 'can-customize-blast'] as const,
  // Saved blasts are scoped to a community or an organizer, not an event: every event's list is
  // invalidated together through the 'saved-blasts' prefix.
  savedBlastsAll: ['saved-blasts'] as const,
  savedBlasts: (eventId: string) => ['saved-blasts', eventId] as const,
  accountPlan: ['account-plan'] as const,
  communityPlan: (id: string) => ['community', id, 'plan'] as const,
};
