export const qk = {
  communities: ['communities'] as const,
  community: (id: string) => ['community', id] as const,
  members: (id: string) => ['community', id, 'members'] as const,
  permissions: (id: string) => ['community', id, 'permissions'] as const,
  posts: (id: string) => ['community', id, 'posts'] as const,
  post: (postId: string) => ['post', postId] as const,
  comments: (postId: string) => ['post', postId, 'comments'] as const,
  reviews: (id: string) => ['community', id, 'reviews'] as const,
  requests: (id: string) => ['community', id, 'requests'] as const,
  suggested: ['communities', 'suggested'] as const,
  canCreate: ['communities', 'can-create'] as const,
  defaultCommunity: ['communities', 'default'] as const,
  groups: (cid: string) => ['community', cid, 'groups'] as const,
  group: (id: string) => ['group', id] as const,
  groupMembers: (id: string) => ['group', id, 'members'] as const,
  groupSeasons: (id: string) => ['group', id, 'seasons'] as const,
  groupInvitations: (id: string) => ['group', id, 'invitations'] as const,
  canCreateGroup: (cid: string) => ['community', cid, 'can-create-group'] as const,
  myGroups: ['my-groups'] as const,
  events: (groupId: string) => ['group', groupId, 'events'] as const,
  communityEvents: (communityId: string) => ['community', communityId, 'events'] as const,
  myEvents: (filter: 'all' | 'organizing' | 'going') => ['my-events', filter] as const,
  event: (id: string) => ['event', id] as const,
  eventParticipants: (id: string) => ['event', id, 'participants'] as const,
  eventInvitations: (id: string) => ['event', id, 'invitations'] as const,
  eventTeams: (id: string) => ['event', id, 'teams'] as const,
  eventRounds: (id: string) => ['event', id, 'rounds'] as const,
  eventMatches: (id: string) => ['event', id, 'matches'] as const,
  eventStandings: (id: string) => ['event', id, 'standings'] as const,
  partnerRequests: (id: string) => ['event', id, 'partner-requests'] as const,
  canCreateEvent: (groupId: string) => ['group', groupId, 'can-create-event'] as const,
  eventRanking: (groupId: string, seasonId: string) =>
    ['group', groupId, 'ranking', seasonId] as const,
  groupRanking: (seasonId: string) => ['group-ranking', seasonId] as const,
  exploreCommunities: ['explore', 'communities'] as const,
  exploreGroups: ['explore', 'groups'] as const,
  exploreEvents: ['explore', 'events'] as const,
  explorePlayers: ['explore', 'players'] as const,
  exploreCommunitiesList: ['explore', 'communities', 'list'] as const,
  exploreGroupsList: ['explore', 'groups', 'list'] as const,
  exploreEventsList: ['explore', 'events', 'list'] as const,
  explorePlayersList: ['explore', 'players', 'list'] as const,
  notifications: ['notifications'] as const,
  notificationsUnread: ['notifications', 'unread'] as const,
  partnerRequestSummary: ['notifications', 'partner-summary'] as const,
  profile: (id: string) => ['profile', id] as const,
  following: (id: string) => ['profile', id, 'following'] as const,
  followers: (id: string) => ['profile', id, 'followers'] as const,
  myProfile: (id: string) => ['profile', id, 'edit'] as const,
  mySettings: (id: string) => ['user-settings', id] as const,
};
