import { beforeAll, describe, it } from 'vitest';
import { query, queryAll, snapshot } from '../driver/a11y';
import { scrollUntilVisible, tap, typeText } from '../driver/actions';
import { expectVisible } from '../driver/expect';
import { freshInstall } from '../driver/app';
import { loginAs, tabTo } from '../driver/flows';
import { select } from '../fixtures/db';
import { pollUntil } from '../fixtures/poll';
import { manifest, resetDb } from '../fixtures/seed';

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

/**
 * The live event screen: rounds and matches, score entry, the timer, the
 * leaderboard, and finishing (with or without counting for group ranking).
 * Uses E3 "Live Mexicano", seeded in progress with round 1 scored, round 2
 * pending and the timer running.
 */
describe('07 event live scoring', () => {
  beforeAll(async () => {
    await resetDb('full');
    await freshInstall();
    await loginAs('alex'); // organizer of E3
    await expectVisible({ text: 'Home', type: 'Heading' }, { timeout: 20_000 });
  });

  const openLive = async () => {
    await tabTo('Events');
    await scrollUntilVisible({ text: /live mexicano/i }, { maxSwipes: 8 });
    await tap({ text: /live mexicano/i });
    await expectVisible({ text: /live mexicano/i }, { timeout: 20_000 });
    await scrollUntilVisible({ text: /view matches/i }, { maxSwipes: 8 });
    await tap({ text: /view matches/i });
    await expectVisible({ text: /matches/i }, { timeout: 20_000 });
  };

  it('shows rounds and matches for an in-progress event', async () => {
    await openLive();
    await expectVisible({ text: /round 1/i });
    // Round 2 was generated by the seed and is unscored.
    await expectVisible({ text: /not scored yet|round 2/i }, { timeout: 15_000 });
  });

  it('submits a score for a pending match', async () => {
    const m = manifest();
    // PostgREST filters cannot contain SQL subqueries — resolve the round ids
    // first, then filter matches by them.
    const rounds = (await select('event_rounds', `event_id=eq.${m.events.e3}&select=id`)) as { id: string }[];
    const roundIds = rounds.map((r) => r.id).join(',');
    // A scored match is status 'played' (not 'completed' — that is the event's
    // own status value; the two vocabularies are different).
    const completedIn = () =>
      select('event_matches', `round_id=in.(${roundIds})&status=eq.played&select=id`);
    const before = ((await completedIn()) as unknown[]).length;
    await scrollUntilVisible({ text: /tap to enter score|not scored yet/i }, { maxSwipes: 6 });
    await tap({ text: /tap to enter score|not scored yet/i });
    await expectVisible({ text: /enter score/i }, { timeout: 15_000 });
    // Points mode: side B is derived from the total, so only side A is typed.
    const field = query(await snapshot(), { type: 'TextField' });
    if (!field) throw new Error('score input not found');
    await typeText({ type: 'TextField' }, '16');
    await tap({ text: /save score/i });
    await pollUntil(
      completedIn,
      (rows) => (rows as unknown[]).length > before,
      { label: 'another match reached played', timeoutMs: 20_000 },
    );
  });

  it('shows the leaderboard', async () => {
    await tap({ text: /leaderboard/i });
    await sleep(1200);
    // Either standings rows or the documented empty state.
    const tree = await snapshot();
    const hasRows = queryAll(tree, { text: /alex organizer|joão pereira|sofia costa/i }).length > 0;
    const empty = query(tree, { text: /no results yet/i });
    if (!hasRows && !empty) throw new Error('leaderboard rendered neither standings nor its empty state');
  });

  // TODO(e2e): the live screen only renders a Timer tab for time-scored events
  // (E3 is points-scored, so its tabs are just Matches/Leaderboard even though
  // the seed starts a timer on it). Needs a fixture with scoring_mode 'time'.
  it.skip('controls the timer', async () => {
    await tap({ text: /timer/i });
    await expectVisible({ text: /pause|start|resume/i }, { timeout: 15_000 });
    const control = query(await snapshot(), { text: /^(pause|resume|start)$/i, type: 'Button' });
    if (!control) throw new Error('no timer control found');
    await tap({ label: control.AXLabel! });
    await sleep(1500);
    // The control must flip to its opposite state.
    const after = query(await snapshot(), { text: /^(pause|resume|start)$/i, type: 'Button' });
    if (after?.AXLabel === control.AXLabel) {
      throw new Error(`timer control did not change state (still "${control.AXLabel}")`);
    }
  });

  it('finishes the event and records the ranking choice', async () => {
    const m = manifest();
    await tap({ text: /matches/i });
    await scrollUntilVisible({ text: /finish event/i }, { maxSwipes: 8 });
    await tap({ text: /finish event/i });
    await expectVisible({ text: /finish (event|early)\?/i }, { timeout: 15_000 });
    // Not every match is scored → the app offers include/exclude from ranking.
    const include = query(await snapshot(), { text: /count for ranking/i });
    await tap({ text: include ? /count for ranking/i : /^finish event$/i });
    await pollUntil(
      () => select('events', `id=eq.${m.events.e3}&select=status`),
      (rows) => (rows as { status: string }[])[0]?.status === 'completed',
      { label: 'event completed', timeoutMs: 25_000 },
    );
  });
});
