import { beforeAll, describe, it } from 'vitest';
import { query, queryAll, snapshot } from '../driver/a11y';
import { scrollUntilVisible, tap, typeText } from '../driver/actions';
import { expectVisible } from '../driver/expect';
import { freshInstall } from '../driver/app';
import { loginAs, tabTo } from '../driver/flows';
import { select } from '../fixtures/db';
import { pollUntil } from '../fixtures/poll';
import { manifest, resetDb } from '../fixtures/seed';

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

/**
 * The live event screen: rounds and matches, score entry, the timer, the
 * leaderboard, and finishing (with or without counting for group ranking).
 * Uses E3 "Live Mexicano", seeded in progress with round 1 scored, round 2
 * pending and the timer running.
 */
describe('07 event live scoring', () => {
  beforeAll(async () => {
    await resetDb('full');
    await freshInstall();
    await loginAs('alex'); // organizer of E3
    await expectVisible({ text: 'Home', type: 'Heading' }, { timeout: 20_000 });
  });

  const openLive = async () => {
    await tabTo('Events');
    await scrollUntilVisible({ text: /live mexicano/i }, { maxSwipes: 8 });
    await tap({ text: /live mexicano/i });
    await expectVisible({ text: /live mexicano/i }, { timeout: 20_000 });
    await scrollUntilVisible({ text: /view matches/i }, { maxSwipes: 8 });
    await tap({ text: /view matches/i });
    await expectVisible({ text: /matches/i }, { timeout: 20_000 });
  };

  it('shows rounds and matches for an in-progress event', async () => {
    await openLive();
    await expectVisible({ text: /round 1/i });
    // Round 2 was generated by the seed and is unscored.
    await expectVisible({ text: /not scored yet|round 2/i }, { timeout: 15_000 });
  });

  /**
   * The only assertion in this suite about WHERE something is rather than whether
   * it exists, and it is here because everything else in the file would have
   * passed while the screen looked wrong.
   *
   * The round-tab strip is a horizontal ScrollView in a column. RN's
   * `baseHorizontal` carries flexGrow: 1, so it claimed the column's spare
   * vertical space and `alignItems: stretch` then stretched each Chip to fill
   * it: a chip measured 176.67pt against an intrinsic 36, and on a one-round
   * event that was a SINGLE chip 176pt tall, pushing the first match from
   * y=194 down to y=335. Every label stayed in the accessibility tree at its new
   * position, so this suite was green throughout.
   *
   * Assert the CHIP, not the strip. A chip is a chip on any device, so 48pt
   * holds regardless of screen height, tab count, or which simulator run.mjs
   * resolved — whereas a threshold on the strip's band, or a ratio of screen
   * height, encodes this machine's geometry and would need re-baselining after
   * any padding change. It is deliberately not a ratchet: there is no value in
   * failing when a chip gets SMALLER, and a ratchet pinned at today's number
   * would have enshrined the 176.67 as correct.
   */
  it('round tabs are chips, not stretched to fill the column', async () => {
    await openLive();
    const tabs = queryAll(await snapshot(), { text: /^round \d+$/i, type: 'Button' });
    if (tabs.length === 0) throw new Error('no round-tab chips on the live screen');
    const tallest = Math.max(...tabs.map((e) => e.frame.height));
    if (tallest > 48) {
      throw new Error(
        `a round tab is ${tallest.toFixed(2)}pt tall — a chip is ~36. The strip is stretching `
        + 'them to fill the column again: check flexGrow on its outer node (live.tsx roundTabsOuter).',
      );
    }
  });

  it('submits a score for a pending match', async () => {
    const m = manifest();
    // PostgREST filters cannot contain SQL subqueries — resolve the round ids
    // first, then filter matches by them.
    const rounds = (await select('event_rounds', `event_id=eq.${m.events.e3}&select=id`)) as { id: string }[];
    const roundIds = rounds.map((r) => r.id).join(',');
    // A scored match is status 'played' (not 'completed' — that is the event's
    // own status value; the two vocabularies are different).
    const completedIn = () =>
      select('event_matches', `round_id=in.(${roundIds})&status=eq.played&select=id`);
    const before = ((await completedIn()) as unknown[]).length;
    await scrollUntilVisible({ text: /tap to enter score|not scored yet/i }, { maxSwipes: 6 });
    await tap({ text: /tap to enter score|not scored yet/i });
    await expectVisible({ text: /enter score/i }, { timeout: 15_000 });
    // Points mode: side B is derived from the total, so only side A is typed.
    const field = query(await snapshot(), { type: 'TextField' });
    if (!field) throw new Error('score input not found');
    await typeText({ type: 'TextField' }, '16');
    await tap({ text: /save score/i });
    await pollUntil(
      completedIn,
      (rows) => (rows as unknown[]).length > before,
      { label: 'another match reached played', timeoutMs: 20_000 },
    );
  });

  it('shows the leaderboard', async () => {
    await tap({ text: /leaderboard/i });
    await sleep(1200);
    // Either standings rows or the documented empty state.
    const tree = await snapshot();
    const hasRows = queryAll(tree, { text: /alex organizer|joão pereira|sofia costa/i }).length > 0;
    const empty = query(tree, { text: /no results yet/i });
    if (!hasRows && !empty) throw new Error('leaderboard rendered neither standings nor its empty state');
  });

  it('finishes the event and records the ranking choice', async () => {
    const m = manifest();
    await tap({ text: /matches/i });
    await scrollUntilVisible({ text: /finish event/i }, { maxSwipes: 8 });
    await tap({ text: /finish event/i });
    await expectVisible({ text: /finish (event|early)\?/i }, { timeout: 15_000 });
    // Not every match is scored → the app offers include/exclude from ranking.
    const include = query(await snapshot(), { text: /count for ranking/i });
    await tap({ text: include ? /count for ranking/i : /^finish event$/i });
    await pollUntil(
      () => select('events', `id=eq.${m.events.e3}&select=status`),
      (rows) => (rows as { status: string }[])[0]?.status === 'completed',
      { label: 'event completed', timeoutMs: 25_000 },
    );
  });
});

/**
 * The Timer tab only exists for TIME-scored events — app/event/[id]/live.tsx
 * gates it on `scoring_mode === 'time'` — and E3 is points-scored, so its tabs
 * are only Matches/Leaderboard even though the seed starts a timer on it. E11
 * "Timed Americano" is the fixture for this and nothing else.
 *
 * Deliberately a separate block: the one above ends by FINISHING E3, so a timer
 * test placed among those tests would either interrupt that flow or navigate it
 * onto the wrong event. This runs afterwards and re-navigates from the Events
 * tab; it inherits the signed-in session (alex, who organizes E11) from the
 * beforeAll above, which vitest has already run in this same file and process.
 */
describe('07b live timer (time-scored event)', () => {
  const openTimedLive = async () => {
    await tabTo('Events');
    await scrollUntilVisible({ text: /timed americano/i }, { maxSwipes: 8 });
    await tap({ text: /timed americano/i });
    await expectVisible({ text: /timed americano/i }, { timeout: 20_000 });
    await scrollUntilVisible({ text: /view matches/i }, { maxSwipes: 8 });
    await tap({ text: /view matches/i });
    await expectVisible({ text: /matches/i }, { timeout: 20_000 });
  };

  it('controls the timer', async () => {
    await openTimedLive();
    await tap({ text: /timer/i });
    await expectVisible({ text: /pause|start|resume/i }, { timeout: 15_000 });
    const control = query(await snapshot(), { text: /^(pause|resume|start)$/i, type: 'Button' });
    if (!control) throw new Error('no timer control found');
    await tap({ label: control.AXLabel! });
    await sleep(1500);
    // The control must flip to its opposite state.
    const after = query(await snapshot(), { text: /^(pause|resume|start)$/i, type: 'Button' });
    if (after?.AXLabel === control.AXLabel) {
      throw new Error(`timer control did not change state (still "${control.AXLabel}")`);
    }
  });
});
